version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
      - image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: calidad2024
    working_directory: ~/repo
    - image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: calidad2024
  ports:
    - "3307:3306"


jobs:
  unit-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Wait for MySQL to Be Ready
          command: |
            for i in `seq 1 10`; do
              nc -z localhost 3307 && echo "MySQL is up" && exit 0
              echo "Waiting for MySQL..."
              sleep 3
            done
            echo "MySQL did not start in time" && exit 1
      - run:
          name: Initialize Database
          command: |
            mysql -h localhost -P 3307 -u root -p123456 calidad2024 < src/test/resources/setup.sql
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Unit Tests
          command: mvn test -Dtest=com.mayab.quality.logginunittest.service.UserServiceTest

          - run:
    name: Wait for MySQL to Be Ready
    command: |
      for i in `seq 1 30`; do
        if nc -z localhost 3307; then
          echo "MySQL is up"
          exit 0
        fi
        echo "Waiting for MySQL..."
        sleep 5
      done
      echo "MySQL did not start in time" && exit 1

      - run:
    name: Debug MySQL Logs
    command: |
      docker logs $(docker ps -q --filter ancestor=mysql:5.7)
          
      - store_test_results:
          path: target/surefire-reports

  selenium-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Selenium Tests
          command: mvn test -Dtest=com.mayab.quality.functional.SeleniumTests
      - store_test_results:
          path: target/surefire-reports

  deploy:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: ./deploy.sh
      - run:
          name: Update GitHub Pages
          command: |
            git config --global user.email "nelsoncaceres98@gmail.com"
            git config --global user.name "Nelson"
            cp -R src/screenshots/* docs/
            git add docs/
            git commit -m "Update GitHub Pages with test results"
            git push origin main

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-tests
      - selenium-tests:
          requires:
            - unit-tests
      - deploy:
          requires:
            - selenium-tests
          filters:
            branches:
              only: main
