version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:17
    working_directory: ~/repo

jobs:
  # Unit tests job
  unit-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Unit Tests
          command: mvn test -Dtest=com.mayab.quality.unittest.service.UserServiceTest
      - store_test_results:
          path: target/surefire-reports

  # Integration tests job
  integration-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Integration Tests
          command: mvn test -Dtest=com.mayab.quality.integration.UserDAOTest
      - store_test_results:
          path: target/surefire-reports

  # Functional tests job
  functional-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Functional Tests
          command: mvn test -Dtest=com.mayab.quality.functional.SeleniumTests
      - store_test_results:
          path: target/surefire-reports
      - persist_to_workspace:
          root: ~/repo
          paths:
            - src/screenshots

  # Publish results job
  publish-results:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Publish Selenium Test Results
          command: |
            git config --global user.email "your-email@example.com"
            git config --global user.name "Your Name"
            mv src/screenshots/* docs/
            git add docs/
            git commit -m "Update test results"
            git push origin main

  # Deployment job
  deploy:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: ./deploy.sh
          - run:
    name: Update GitHub Pages
    command: |
      git config --global user.email "your-email@example.com"
      git config --global user.name "Your Name"
      cp -R src/screenshots/* docs/
      git add docs/
      git commit -m "Update GitHub Pages with test results"
      git push origin main

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-tests
      - integration-tests:
          requires:
            - unit-tests
      - functional-tests:
          requires:
            - integration-tests
      - publish-results:
          requires:
            - functional-tests
      - deploy:
          requires:
            - publish-results
          filters:
            branches:
              only: main
