version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unittest
    working_directory: ~/repo

jobs:
  unit-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Wait for MySQL to Be Ready
          command: |
            for i in `seq 1 10`; do
              nc -z localhost 3306 && echo "MySQL is up" && exit 0
              echo "Waiting for MySQL..."
              sleep 3
            done
            echo "MySQL did not start in time" && exit 1
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Unit Tests
          command: mvn test -Dtest=com.mayab.quality.logginunittest.service.UserServiceTest
      - store_test_results:
          path: target/surefire-reports

  selenium-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Selenium Tests
          command: mvn test -Dtest=com.mayab.quality.functional.SeleniumTests
      - store_test_results:
          path: target/surefire-reports

  deploy:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: ./deploy.sh
      - run:
          name: Update GitHub Pages
          command: |
            git config --global user.email "your-email@example.com"
            git config --global user.name "Your Name"
            cp -R src/screenshots/* docs/
            git add docs/
            git commit -m "Update GitHub Pages with test results"
            git push origin main

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-tests
      - selenium-tests:
          requires:
            - unit-tests
      - deploy:
          requires:
            - selenium-tests
          filters:
            branches:
              only: main

