version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  unit-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test -Dtest=com.mayab.quality.logginunittest.service.UserServiceTest
      - store_test_results:
          path: target/surefire-reports

  deploy:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: ./deploy.sh
      - run:
          name: Update GitHub Pages
          command: |
            git config --global user.email "nelsoncaceres98@gmail.com"
            git config --global user.name "Nelson"
            cp -R src/screenshots/* docs/
            git add docs/
            git commit -m "Update GitHub Pages with test results"
            git push origin main

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-tests
      - deploy:
          requires:
            -unit-test-
          filters:
            branches:
              only: main
