version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
