version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:17
    working_directory: ~/repo

jobs:
  # Unit tests job
  unit-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Unit Tests
          command: mvn test -Dtest=com.mayab.quality.unittest.service.UserServiceTest
      - store_test_results:
          path: target/surefire-reports

  # Integration tests job
  integration-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Integration Tests
          command: mvn test -Dtest=com.mayab.quality.integration.UserDAOTest
      - store_test_results:
          path: target/surefire-reports

  # Functional tests job
  functional-tests:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn install
      - run:
          name: Run Functional Tests
          command: mvn test -Dtest=com.mayab.quality.functional.SeleniumTests
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-tests
      - integration-tests:
          requires:
            - unit-tests
      - functional-tests:
          requires:
            - integration-tests
